Provide stubs
exercism/php pull request #357
Opened 2021-03-24 23:21 UTC by codedge

2021-03-25 14:35 UTC, codedge commented
I ran through all the exercises adding stubs. Should be good now.

2021-03-26 12:46 UTC, neenjaw commented
@codedge - Thanks for opening this PR! I'll review this tonight. From a brief skim, this looks great!

2021-03-26 14:08 UTC, neenjaw requested changes

2021-03-26 14:08 UTC, neenjaw commented on exercises/practice/accumulate/Accumulate.php
> +    \BadFunctionCallException("Implement the accumulate function");
Shouldn't these throw the error?
```suggestion
    throw new \BadFunctionCallException("Implement the accumulate function");
```

2021-03-26 22:14 UTC, codedge commented on exercises/practice/accumulate/Accumulate.php
> +    \BadFunctionCallException("Implement the accumulate function");
Holy... your are completely right. Fixed for all the tests.

2021-03-27 03:13 UTC, neenjaw approved these changes
Very nice! Awesome work @codedge!

2021-03-27 03:16 UTC, merged