Optimise palindrome-products example for speed
exercism/php pull request #364
Opened 2021-04-17 14:10 UTC by zembrowski

The palindrome-products example takes around [75% of the running time](https://github.com/exercism/php/pull/363/checks?check_run_id=2360574137#step:6:374) in the CI test pipeline and a up to several minutes on local machines. With the introduced changes the tests run 1m50s faster in the pipeline.

Changes based on some [exercism solutions](https://exercism.io/tracks/php/exercises/palindrome-products/solutions/09c958495eeb4aad8e1acf1e5c33ab68).

2021-04-17 19:42 UTC, neenjaw requested changes
Looks great.  These examples haven't been touched in a long time so there is definitely room for improvement here!

I left a couple questions in the review.

2021-04-17 19:42 UTC, neenjaw commented on exercises/practice/palindrome-products/.meta/example.php
>  function smallest($min, $max)
We've since added types to the stub file (which will be served to students when exercism's new version goes live next month). Could you add types to this file since we are making changes to it right now?

2021-04-17 19:42 UTC, neenjaw commented on exercises/practice/palindrome-products/.meta/example.php
> +    $r = generatePalindromeProducts(range($min, $max));
can we give a meaningful name to `$r`?

2021-04-17 19:42 UTC, neenjaw commented on exercises/practice/palindrome-products/.meta/example.php
>              if (isPalindrome($n)) {
Is there an opportunity here to improve the naming of `$x`, `$y`, or `$n`?

2021-04-19 12:47 UTC, zembrowski commented on exercises/practice/palindrome-products/.meta/example.php
>  function smallest($min, $max)
Types added.

2021-04-19 12:47 UTC, zembrowski commented on exercises/practice/palindrome-products/.meta/example.php
> +    $r = generatePalindromeProducts(range($min, $max));
Changed to `$product`

2021-04-19 12:49 UTC, zembrowski commented on exercises/practice/palindrome-products/.meta/example.php
>              if (isPalindrome($n)) {
Changed `$n` to `$number`. Did not come up with any meaningful replacements for `$x` and `$y`.

2021-04-19 13:46 UTC, neenjaw approved these changes

2021-04-19 13:47 UTC, merged