Add constructor template in LargestSeriesProduct.php
exercism/php pull request #576
Opened 2023-11-07 10:41 UTC by realwahl

The tests imply that the Series class has a constructor with a string parameter. If we provide a class template, we should provide a template for the constructor as well.

2024-02-16 19:30 UTC, mk-mxp commented
@realwahl Are you willing to make this mergable?

2024-02-18 15:49 UTC, homersimpsons commented
@realwahl Tests are failing because a `[tab]` is used on line 30 instead of 4 spaces. Do you have time to fix this ?

2024-02-18 15:49 UTC, homersimpsons requested changes

2024-02-18 15:49 UTC, homersimpsons commented on exercises/practice/largest-series-product/LargestSeriesProduct.php
> +	{
Replace tab by 4 spaces:
```suggestion
    {
```

2024-02-18 17:11 UTC, realwahl commented
I will check, thanks!

On Sun, 18 Feb 2024, 16:49 homersimpsons, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In exercises/practice/largest-series-product/LargestSeriesProduct.php
> <https://github.com/exercism/php/pull/576#discussion_r1493793250>:
>
> > @@ -26,6 +26,11 @@
>
>  class Series
>  {
> +    public function __construct(string $input)
> +	{
>
> Replace tab by 4 spaces:
> ⬇️ Suggested change
>
> -	{
> +    {
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/exercism/php/pull/576#pullrequestreview-1887269321>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFK3NEHXAWP3PROUENEZ5JTYUIPJBAVCNFSM6AAAAAA7A6VU6CVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQOBXGI3DSMZSGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-02-18 22:12 UTC, realwahl commented
@mk-mxp  I think it should be ok now, can you please check?
@homersimpsons Thanks a lot!

2024-02-18 23:23 UTC, homersimpsons approved these changes

2024-02-18 23:23 UTC, merged