Put all code styling rules into PHPCS config
exercism/php pull request #591
Opened 2023-12-06 13:36 UTC by mk-mxp

- Add XML namespace for completeness
- Remove non-existent `type="int"`
- Add directory rules for improved test coverage and required exceptions
- Fix the new upcoming violations

This is part of the discussion in [the forum](https://forum.exercism.org/t/php-streamlining-php-codesniffer-usage/8538).

2023-12-06 15:05 UTC, neenjaw requested changes
Couple small changes needed. I'm fine with putting it in one place.

2023-12-06 15:05 UTC, neenjaw commented on exercises/concept/city-office/.meta/exemplar/Form.php
This exercise is intentional without visibility modifiers

2023-12-06 15:05 UTC, neenjaw commented on exercises/concept/windowing-system/.meta/exemplar.php
This exercise is intentional without visibility modifiers

2023-12-06 17:09 UTC, mk-mxp commented
Should I do these also?
* Rename the config file to `phpcs.xml`, so it is not necessary to specify it
* Remove `bin/install*.sh` and `bin/lint.sh`, these seem overly complicated and are only used for README instructions. Instead we should point to the track instructions https://exercism.org/docs/tracks/php/installation#h-install-composer and use `composer install`

2023-12-09 10:27 UTC, mk-mxp commented
@neenjaw I think, GitHub is confused because I'm not assigned to this PR and so my changes do not count for review resolving.

2023-12-27 10:54 UTC, mk-mxp commented
@neenjaw The latest version of PHP CodeSniffer is not compatible to the latest Slevomat Coding Standard. I did exclude the updated PHP CodeSniffer for installation, but that is of course only temporary.

2023-12-27 11:21 UTC, mk-mxp commented
Problem:

> "Invalid sniff properties set for individual sniffs will now result in an error and halt the execution of PHPCS"
> PHPCodeSniffer Release notes V3.8.0

Solution:

- [x] Change Slevomat Sniff property to current name

2023-12-27 14:07 UTC, neenjaw commented
Can you cherry pick a patch to fix ci to a separate pr to unblock the other prs?

I haven't had time to review this one as it comprises a more complex change for the track.

2023-12-28 17:59 UTC, mk-mxp commented
Rebased to solve merge conflicts.

Might it help to split this PR into 2 or 3? One with the rules / changes due to rules, one with the README and contribution workflow changes and maybe the removal of the old script also in one extra?

What I checked for workflow changes / script removal:

- This projects CI does not use the removed scripts. It uses [composer for PHP CodeSniffer](https://github.com/exercism/php/blob/f0f182d0c302a6e20340390a7c75a8ed72d91a5f/.github/workflows/exercise-lint-phpcs-psr-12.yml#L43) and direct [PHAR download for PHPUnit](https://github.com/exercism/php/blob/f0f182d0c302a6e20340390a7c75a8ed72d91a5f/.github/workflows/exercise-tests-phpunit-9.yml#L38)
- [PHP test runner](https://github.com/exercism/php-test-runner/blob/61252274d05daf021fa70c6166edc1b9a0d1ce63/Dockerfile#L12) does it's own thing
- [PHP representer](https://github.com/exercism/php-representer) also has nothing to do with these workflow files
- I haven't found any hint on CI workflows other than `configlet` stuff in Exercism's documentation
- We use `composer` during contribution workflow (locally and in CI) only, with no potential for package version conflicts because of the nature of the exercises
- `composer` is the only tool used for contribution now, running the exact same things in CI and locally (if locally up-to-date, of course)

2024-02-16 19:22 UTC, mk-mxp commented
@ErikSchierboom Please advise on the following:

This MR changes the contribution workflow for the PHP track massively. One part is removing `install.sh` and `install-*` completely. They are not used in CI since long and now replaced by `composer install` for contributors.

Does this have any negative impact on you or other parts of exercism (e.g. mass MRs)?

2024-02-18 15:44 UTC, homersimpsons requested changes
Let's get this merged, I did suggest some re-wording, feel free to discuss them.

2024-02-18 15:44 UTC, homersimpsons commented on README.md
> +If you only want to solve the exercises, go to the [track docs][track-docs] and choose your installation option there.
```suggestion
Follow these instructions to contribute to the PHP track.

To solve the execise, head to the [PHP track](https://exercism.org/tracks/php) and check the [documentation][track-docs].
```

2024-02-18 15:44 UTC, homersimpsons commented on README.md
> +You must have installed `composer` as a global tool as recommended in the [PHP track installation docs][composer-installation-docs].
```suggestion
The following system dependencies are required:
- `composer`, as recommended in the [PHP track installation docs][composer-installation-docs].
- [`bash` shell](https://www.gnu.org/software/bash/)
```

2024-02-18 15:44 UTC, homersimpsons commented on README.md
> +composer install
```suggestion
Run the following command to get started with this project:

```shell
bin/fetch-configlet # The official tool for managing Exercism language track repositories
composer install # Required dependencies to develop this track
```

2024-02-18 15:44 UTC, homersimpsons commented on README.md
> +You now have all tools required to contribute.
```suggestion
```

2024-02-18 15:44 UTC, homersimpsons commented on README.md
> +We use PHPUnit 9.6.x and a shell loop injecting `exemplar.php` as the solution for testing:
```suggestion
The tests are run with PHPUnit. A shell loop injecting `exemplar.php` is provided to ease testing.

Execute the following command to run the tests:
```

2024-02-18 15:44 UTC, homersimpsons commented on README.md
> +composer lint:fix
```suggestion
This project use a slightly [modified] version of [PSR-12], use the following commands to apply code style:
```shell
composer lint:check # Checks the files against the code style rules
composer lint:fix # Automatically fix codestyle issues
```

2024-02-18 15:44 UTC, homersimpsons commented on phpcs.xml
> +  <arg name="parallel" value="10" />
I like to use a value of 60, it does a full line and better scale with a lot of core.
```suggestion
  <!-- Run on 60 files in parallel -->
  <arg name="parallel" value="60" />
```

2024-02-18 18:22 UTC, mk-mxp commented on phpcs.xml
> +  <arg name="parallel" value="10" />
I didn't see any difference on my computer, 1.5 seconds anyways. But that's no value I care for...

2024-02-18 18:46 UTC, homersimpsons approved these changes

2024-02-18 18:46 UTC, merged