Overhaul `basic-syntax` and `lasagna`
exercism/php pull request #607
Opened 2024-01-30 14:30 UTC by mk-mxp

This very first concept and its concept exercise touch a lot of concepts coming later.
These must be introduced as much as necessary to understand the code and the requested solution, but not more.
So we have many short introductions and a bit more depth for the `about.md`. But what is "Basics" or "basic-syntax" then?

The important decision guiding document (according to exercisms docs) is `design.md`, which was a copy from the Ruby track and not adjusted for PHP Basics. I analyzed the exercise (as this must remain mostly the same to not invalidate solutions) and re-wrote `design.md` to inform further decisions. And answered the question "what to teach here" from this perspective.

I then added missing conceptual information to `about.md` for little experienced programmers and condensed that document for `introduction.md` to address medium experienced programmers. I kept the chapter on code organisation in `about.md` and added a chapter on simple debugging. As I think this helps people who are stuck also, I added `var_dump()` to `hints.md`.

I focused the exercise stub on doing the function bodies for the tasks from `instructions.md` by adding method definitions without body. As outlined in `design.md` I think it is not "basic syntax" to define the interface of methods, that is "user-defined functions" and "class basics".

I intentionally chose comments for the function bodies and not throwing exceptions, as that would add another concept to touch.

Finally I added more value to the exercise tests by making their feedback more helpful and guiding.

- [x] The concept has its own concept exercise
- [x] The concepts configuration integrates nicely into the concept map
  - [x] The name and subtext (blurb) read well together
  - [x] ~~The concept is connected to the prerequisite concepts as planned~~ (has none)
- [x] The concept follows exercism guidelines
  - [x] `about.md` for in-depth discussion of the topic
  - [x] `introduction.md` with concise information to address a medium experienced programmer who is new to PHP
  - [x] `introduction.md` links to `about.md` for those who need / want more information
- [x] The concept exercise follows exercism guidelines
  - [x] `design.md` outlines goals, learning objectives, scope, unlocked concepts, prerequisites
  - [x] Re-use introduction from concept
  - [x] `instructions.md` uses steps to drive towards the solution
  - [x] `hints.md` unstucks programmers without handing out the solution, mostly by refering to helpful sources to read
  - [x] `hints.md` links back to `about.md` where reasonable
- [x] The concept exercise uses only concepts already introduced
- [x] The concept exercise adheres to PHP track consensus:
  - [x] Use classes, not functions
  - [x] Names are in unified casing (classes PascalCase, methods camelCase, variables snake_case)
  - [x] Strict types in tests (and optionally in exemplar), but not in students files (the concept to be mastered is still missing)
- [x] The tests make sense and are helpful to master the exercises
  - [x] Order of tests matches the order of instructions
  - [x] Failing tests give helpful information

2024-01-30 14:31 UTC, mk-mxp commented
I'm not sure about re-arranging the tests to follow [Arrange, Act, Assert](https://wiki.c2.com/?ArrangeActAssert) or [Given, When, Then](https://martinfowler.com/bliki/GivenWhenThen.html) with additionally separated out input and expected values. The arrangement would allow easier implementation of a test generator for practice exercises, students would get used to seeing a test arrangement recommended for unit testing and many implementation details look much nicer when separating the data from the phases.

Current code:

```php
    public function testTotalElapsedTime(): void
    {
        $lasagna = new Lasagna();
        $this->assertEquals(21, $lasagna->totalElapsedTime(layers_to_prep: 4, elapsed_minutes: 13));
    }
```

Arrange-Act-Assert:

```php
    public function testTotalElapsedTime(): void
    {
        $input = [
            'layers_to_prep' => 4,
            'elapsed_minutes' => 13,
        ];
        $expected = 21;

        $subject = new Lasagna();
        $actual = $subject->totalElapsedTime(...$input);

        $this->assertEquals($expected, $actual);
    }
```

Also I would suggest using a common naming scheme for the tests. E.g. I usually use `$expected`, `$actual`, `$subject` (rather than `$subjectUnderTest` or `$sut`) like shown in the example above.

2024-02-15 23:34 UTC, homersimpsons requested changes
Overall a great improvemen! I opened some threads on things I think we can improve.

Do not hesitate to discuss them.

2024-02-15 23:34 UTC, homersimpsons commented on concepts/basic-syntax/about.md
> +If the file contains only PHP code, there is no closing tag `?>` to mark the end of PHP code.
```suggestion
If the file contains only PHP code, it is possible to omit the closing tag `?>` which is used to mark the end of PHP code.
```

2024-02-15 23:34 UTC, homersimpsons commented on concepts/basic-syntax/about.md
> +$message = "Success!"; // Statement correctly ends with `;`
I think it is relevant to keep the opening `<?php` tags in this introduction or clearly state that we will omit them for readability.

2024-02-15 23:34 UTC, homersimpsons commented on concepts/basic-syntax/about.md
> +}
It certainly makes more sense to declare the function at the beginning, unless the goal is to showcase that declaration order is not relevant.

```suggestion
// declare the window_width function
function window_width($width)
{
    echo $width; // Access the value passed into the function as $width
    // ...
}

window_width(100); // Call the function with the literal value 100

$newWidth = 100;
window_width($newWidth); // Call the function withthe value stored in $newWidth
```

2024-02-15 23:34 UTC, homersimpsons commented on concepts/basic-syntax/about.md
> +// => 2
```suggestion
$result = $calculator->sub(3, 1); // Calls the method sub() of the instance stored in $calculator
echo $result; // => 2
```

2024-02-15 23:34 UTC, homersimpsons commented on concepts/basic-syntax/about.md
> +- `print $variable;`, which is the same as `echo $variable;`
I do not find `print` to be common, do we want to show it here ?

2024-02-15 23:34 UTC, homersimpsons commented on concepts/basic-syntax/about.md
> +It is common practice to have one class per file with a filename which matches the class.
Do we want to add a reference to PSR-4 ? It may be too confusing though.

2024-02-15 23:34 UTC, homersimpsons commented on concepts/basic-syntax/introduction.md
> +// => 110
```suggestion
$result = window_height(100);
echo $result; // => 110
```

2024-02-15 23:34 UTC, homersimpsons commented on exercises/concept/lasagna/.docs/hints.md
> +- You can use the [mathematical operator for subtraction][php-operators] to subtract values.
```suggestion
- You can use the [mathematical operator for subtraction][php-operators] `-` to subtract values.
```

2024-02-15 23:34 UTC, homersimpsons commented on exercises/concept/lasagna/.docs/hints.md
> +- You can use the [mathematical operator for multiplication][php-operators] to multiply values.
```suggestion
- You can use the [mathematical operator for multiplication][php-operators] `*` to multiply values.
```

2024-02-15 23:34 UTC, homersimpsons commented on exercises/concept/lasagna/.docs/hints.md
> +- You can use the [mathematical operator for addition][php-operators] to add values.
```suggestion
- You can use the [mathematical operator for addition][php-operators] `+` to add values.
```

2024-02-15 23:34 UTC, homersimpsons commented on exercises/concept/lasagna/.docs/introduction.md
> +// => 110
```suggestion
$result = window_height(100);
echo $result; // => 110
```

2024-02-15 23:34 UTC, homersimpsons commented on exercises/concept/lasagna/.docs/introduction.md
> +// => 2
```suggestion
$result = $calculator->sub(3, 1); // Calls the method sub() of the instance stored in $calculator
echo $result; // => 2
```

2024-02-15 23:34 UTC, homersimpsons commented on exercises/concept/lasagna/LasagnaTest.php
> + * - Please use `assertSame()` whenever possible. Note reasons for exceptions.
```suggestion
 * - Please use `assertSame()` whenever possible. Add a comment when it is not possible.
```

2024-02-15 23:34 UTC, homersimpsons commented on exercises/concept/lasagna/LasagnaTest.php
> +        $this->assertEquals(10, $lasagna->remainingCookTime(elapsed_minutes: 30));
(see named argurment discussion)

2024-02-15 23:34 UTC, homersimpsons commented on exercises/concept/lasagna/LasagnaTest.php
> +        $this->assertEquals(14, $lasagna->totalPreparationTime(layers_to_prep: 7));
(see named argurment discussion)

2024-02-15 23:34 UTC, homersimpsons commented on exercises/concept/lasagna/LasagnaTest.php
> +        $this->assertEquals(21, $lasagna->totalElapsedTime(layers_to_prep: 4, elapsed_minutes: 13));
(see named argurment discussion)

2024-02-16 21:01 UTC, mk-mxp commented on concepts/basic-syntax/about.md
> +- `print $variable;`, which is the same as `echo $variable;`
I have seen `print` in quite some PHP code, in one company even as must-have in coding styles. As much as I prefer `echo` myself, it seems to _feel better_ for native speakers or users of other languages. This is the only place I mention it, it's not in the `introduction.md` nor in the tracks `debug.md`. So I'd leave it in here for completeness, but not promote it further.

2024-02-16 21:10 UTC, mk-mxp commented on concepts/basic-syntax/about.md
> +It is common practice to have one class per file with a filename which matches the class.
I am not sure, if adding a reference to a topic like autoloading (PSR-4 is just one convention using files with matching class names) distracts too much from the basics to learn. I would rather take out the whole `Code organization` topic than adding more to it. Are you OK with leaving PSR-4 for the namespace concept?

2024-02-16 21:15 UTC, mk-mxp commented on exercises/concept/lasagna/.docs/hints.md
> +- You can use the [mathematical operator for subtraction][php-operators] to subtract values.
I'm not sure about adding the concrete operator to the hints. In the [exercism docs](https://exercism.org/docs/building/tracks/concept-exercises#h-file-docs-hints-md), it says:

> The hints should not spell out the solution, but instead point to a resource describing the solution

To me, adding the concrete operator is _spelling out the solution_. Do you agree?

2024-02-16 21:23 UTC, mk-mxp commented on exercises/concept/lasagna/.docs/introduction.md
> +// => 110
This type of showing the resulting value of the previous operation is used across all PHP concept exercises. In fact, `echo` cannot be used for `false` or `''` or complex values in arrays / objects. So I kept this notation as it is a compromise between code correctness and understandability. And it is [used in other languages as well](https://github.com/exercism/javascript/blob/main/exercises/concept/lasagna/.docs/instructions.md#2-calculate-the-remaining-oven-time-in-minutes).

2024-02-16 21:27 UTC, mk-mxp commented on exercises/concept/lasagna/LasagnaTest.php
> +        $this->assertEquals(21, $lasagna->totalElapsedTime(layers_to_prep: 4, elapsed_minutes: 13));
Can you point to a resurce for the "named argurment discussion"? It's not in GitHub issues. Forum? Discord?

2024-02-17 13:37 UTC, homersimpsons commented on exercises/concept/lasagna/.docs/hints.md
> +- You can use the [mathematical operator for subtraction][php-operators] to subtract values.
Okay, I'm fine with that. It avoid duplicating the doc and shows the student where to look for ressources.

2024-02-17 13:38 UTC, homersimpsons commented on exercises/concept/lasagna/.docs/introduction.md
> +// => 110
Okay, makes sense then, let's keep it like this and be consistent with the rest.

2024-02-17 13:39 UTC, homersimpsons commented on concepts/basic-syntax/about.md
> +It is common practice to have one class per file with a filename which matches the class.
> Are you OK with leaving PSR-4 for the namespace concept?

Okay to do it in this concept.

2024-02-17 13:44 UTC, homersimpsons commented on exercises/concept/lasagna/LasagnaTest.php
> +        $this->assertEquals(21, $lasagna->totalElapsedTime(layers_to_prep: 4, elapsed_minutes: 13));
> Can you point me to a resource for the "named argument discussion"? It's not in GitHub issues. Forum? Discord?

Woops, looks like I did not comment it in any case.

I'm against using named arguments in the test. In fact, a student may change the arguments' names and then the tests will break.

So to me we should not test that the argument names are correct.

What to you think ?

2024-02-17 15:18 UTC, mk-mxp commented on exercises/concept/lasagna/LasagnaTest.php
> +        $this->assertEquals(21, $lasagna->totalElapsedTime(layers_to_prep: 4, elapsed_minutes: 13));
Using positional parameters in later concept exercises is my goal, as you can see from the DocBlock above the test class asking for not using them. But I forgot to write down the rational about why I use them here...will add that.

I wanted to use named arguments in the first concept exercises to help students see the connection between the value in the test code and the parameter name of the function. This is because in `about.md`, `introduction.md` and `instructions.md` we introduce the general idea of using the parameter name as a variable in the function body, but not that parameter position is relevant. It is not like this in all languages. And I think that this rather abstract explanation would not stick long enough until required for solving the exercise.

I wanted to introduce these details in `user-defined-functions` concept, when showing named vs. positional parameters using optional parameters. That will be shortly after the basic types in the concept tree. And not use named parameters after that anymore.

2024-02-17 16:32 UTC, homersimpsons commented on exercises/concept/lasagna/LasagnaTest.php
> +        $this->assertEquals(21, $lasagna->totalElapsedTime(layers_to_prep: 4, elapsed_minutes: 13));
I understand your point, wouldn't this add additional burden if a student changes the parameter name ?

Would it make sense to duplicate the tests to have one with positional argument and the other one with named arguments ?

> This is because in `about.md`, `introduction.md` and `instructions.md` we introduce the general idea of using the parameter name as a variable in the function body, but not that parameter position is relevant.

We are not showing named arguments here. I think if a student reads the test code he may be a bit lost reading the argument names here.

> wanted to introduce these details in `user-defined-functions` concept, when showing named vs. positional parameters using optional parameters. That will be shortly after the basic types in the concept tree. And not use named parameters after that anymore.

Are we in `user-defined-functions` concept here ?

2024-02-17 17:32 UTC, mk-mxp commented on exercises/concept/lasagna/LasagnaTest.php
> +        $this->assertEquals(21, $lasagna->totalElapsedTime(layers_to_prep: 4, elapsed_minutes: 13));
OK then, named arguments are gone. I still believe in the value of named arguments for understandig which value goes where. But I do not have data to proof my point as well I have no data to proof the opposite.

2024-02-17 17:37 UTC, homersimpsons approved these changes

2024-02-17 17:43 UTC, merged

2024-02-17 17:43 UTC, homersimpsons commented
Thank you very much for all those improvements !