Add Rotational Cipher Exercise
exercism/php pull request #635
Opened 2024-02-22 20:14 UTC by tomasnorre

We didn't agree on this, either. But here it is.

http://forum.exercism.org/t/implement-some-missing-php-exercises-for-48in24/9865/11

2024-02-22 21:59 UTC, mk-mxp requested changes
Thanks a lot! And such a high quality of your contribution. Your code is nice to read.

2024-02-22 21:59 UTC, mk-mxp commented on exercises/practice/rotational-cipher/.docs/instructions.md
> +- ROT13 `Gur dhvpx oebja sbk whzcf bire gur ynml qbt.` gives `The quick brown fox jumps over the lazy dog.`
OK, ROT13 is in the tests. Maybe we should add a statement against using `str_rot13()` or other PHP encoding functions. Do not append it to this file, as this breaks the sync between problem specification and the track exercise.

Add a new file `.docs/instructions.append.md` with something like this:

```markdown
~~~~exercism/note
Do not use PHP functions like `str_rot13()` to solve this exercise! Only use basic string and character manipulation functions.
~~~~

2024-02-23 12:32 UTC, merged

2024-02-23 12:43 UTC, neenjaw commented on exercises/practice/rotational-cipher/.docs/instructions.md
> +- ROT13 `Gur dhvpx oebja sbk whzcf bire gur ynml qbt.` gives `The quick brown fox jumps over the lazy dog.`
I disagree with strictly preventing some solutions that utilize built in parts of the language. 

I have seen this approach on other tracks and it tends to evolve into a race where maintainers have to then built specific tooling to catch "cheaters" or disable the standard library which is a waste of our limited time. These students only cheat themselves and I think we can encourage the behaviour we want to see positively. 

I think this could be worded:

> PHP has built-in functions to perform string encoding. For an additional challenge, try to solve this problem without using `str_rot13()`.

I think it would also be fair to add Ana additional warning to not use these functions if you need secure encoding.

2024-02-23 13:00 UTC, tomasnorre commented
> Thanks a lot for contributing! You must tell me, which AI you use to produce that good code so fast...

ChatGPT, it was that obvious. :) I'm taking existing exercises from other languages and convert the tests and example, and adjust to my liking. It's faster this way.

2024-02-23 15:51 UTC, tomasnorre commented
> By default all prs are scored as a medium, I think mkmxp scored some of these as a large? Without tags they don't get attributed to a specific sub-category.

No Problem, thought it has something to do with the tagging, and you confirmed that.

2024-02-23 16:47 UTC, mk-mxp commented
@tomasnorre Yes, all my bad. Was too much in hurry this morning. Will take more time and be more cautious.

2024-02-23 16:58 UTC, neenjaw commented
Tags can be added retroactively and it will update.

2024-02-23 17:00 UTC, tomasnorre commented
> @tomasnorre Yes, all my bad. Was too much in hurry this morning. Will take more time and be more cautious.

Not a huge deal, but must admit the gamification motivates me too :)

2024-02-23 17:16 UTC, mk-mxp commented
Thanks for the info, @neenjaw !