Add Two Bucket Exercise
exercism/php pull request #636
Opened 2024-02-22 21:02 UTC by tomasnorre

We didn't agree on this, either. But here it is. Feel a little like a rebel not following orders.

http://forum.exercism.org/t/implement-some-missing-php-exercises-for-48in24/9865/11

2024-02-22 22:03 UTC, mk-mxp commented
> We didn't agree on this, either. But here it is. Feel a little like a rebel not following orders.

Is that a good feeling to you? You do not have to apologize for the many useful work you contribute. You are welcome!

2024-02-23 07:50 UTC, tomasnorre commented
> > We didn't agree on this, either. But here it is. Feel a little like a rebel not following orders.
> 
> Is that a good feeling to you? You do not have to apologize for the many useful work you contribute. You are welcome!

Am not feeling good or bad, just a feeling, that I'm not really following the normal process of asking before doing.

2024-02-23 08:02 UTC, tomasnorre commented on exercises/practice/two-bucket/TwoBucket.php
> +class TwoBucket
1) I agree with you, arrays are not the best for storing and returning data, I always post back to this [1][2] when discussion it, and old colleague of mine wrote it. So I'm OK with an object of some kind too? But thought of the faster solution, not the most elegant, which I probably should have. I don't have an idea from the top of my head what the object should be call, and if it should only hold the return values? Should it simply be the `TwoBucket` object with 3 additional properties? 

2) I was really in doubt how much of the `Bucket`-class should stay in the stub, if any. So I'm totally OK with discussion it. It's for sure a matter of how one sees the implementation, and not required either by specs nor tests. So I'm OK with removing that and leave it completely to the student. 

1: https://www.phparch.com/article/never-use-arrays/
2: https://presentations.garfieldtech.com/slides-never-use-arrays/phpday2021/

2024-02-23 12:31 UTC, neenjaw commented on exercises/practice/two-bucket/TwoBucket.php
> +class TwoBucket
Yea, I hear your argument about avoiding the use of an array in place of a struct.

I think it'd be reasonable to provide an interface for the result object so you can write the test or rely on a duck-typing run time error to communicate the interface if you want to avoid an array return value

2024-02-23 12:43 UTC, mk-mxp commented on exercises/practice/two-bucket/TwoBucket.php
> +class TwoBucket
OK, I'll summarise: @tomasnorre Please remove the `Bucket` stub and suggest a solution for returning the result cohesively, but not in an array. The solution shall give clear hints on what to do when a test fails because of an interface violation. This can be done by methods or properties on a result object or similar, with duck typing or declaring a real `interface` type to refer to. Also have in mind, that the online editor displays failures to students very differently as you see them on CLI.

2024-02-23 13:18 UTC, tomasnorre commented on exercises/practice/two-bucket/TwoBucket.php
> +class TwoBucket
I have submitted a draft, I hope I understood you correctly.

2024-02-23 17:11 UTC, mk-mxp approved these changes

2024-02-23 17:11 UTC, mk-mxp commented on exercises/practice/two-bucket/.meta/example.php
> +    public int $otherBucket;
As we have only one shot for the interface, let's make the property names very clear:

```suggestion
    public int $numberOfActions;
    public string $nameOfBucketWithDesiredLiters;
    public int $litersLeftInOtherBucket;
```

About the first value: the instructions talk about actions, not moves. On the second value: the word goal doesn't appear in the instructions, they are always about "desired liters" or "exact liters". And the last values is the liters, not the number of the bucket. I hope that's clear enough for any student.

2024-02-23 17:11 UTC, mk-mxp commented on exercises/practice/two-bucket/TwoBucket.php
> +class TwoBucket
Properties on the object are chosen. That's OK with me. I wouldn't return `$this`, because one can call `->solve()` only when one has the instance already. And you don't use that return in the tests.

I'll give @neenjaw a chance to comment on the interface, it looks fine to me now.

2024-02-23 17:11 UTC, mk-mxp requested changes
Sorry, wrong selection.

2024-02-24 07:18 UTC, tomasnorre commented on exercises/practice/two-bucket/TwoBucket.php
> +class TwoBucket
>  I wouldn't return $this, because one can call ->solve() only when one has the instance already. And you don't use that return in the tests.

I do use the result in the tests currently `$result = $twoBucket->solve();` but that can of course be changed.

2024-02-24 08:24 UTC, mk-mxp commented on exercises/practice/two-bucket/TwoBucket.php
> +class TwoBucket
My bad again, maybe I had the exception tests in mind. `I wouldn't return $this` means: You can do so, because that's fine, too. But I wouldn't. I would use a typed result object with only those properties.

2024-02-24 08:28 UTC, mk-mxp requested changes

2024-02-24 08:28 UTC, mk-mxp commented on exercises/practice/two-bucket/TwoBucket.php
> +    public function solve(): self
Good, that we discussed again. Please remove the return type, so the students are not primed to think this is a must-have. They should be able to return whatever type they like.

2024-02-24 08:42 UTC, tomasnorre commented on exercises/practice/two-bucket/TwoBucket.php
> +class TwoBucket
> I would use a typed result object with only those properties.

I'm OK with that too, but what is the object called? I couldn't come up with anything good, so decide on the `TwoBucket` object extended with the additional properties.

2024-02-24 09:22 UTC, mk-mxp commented on exercises/practice/two-bucket/TwoBucket.php
> +class TwoBucket
OK, then. Let's make it a tutorial session on my naming rational :smiley: 

I would have used this:

```php
class Solution
{
    public function __construct(
        public int $numberOfActions,
        public string $nameOfBucketWithDesiredLiters,
        public int $litersLeftInOtherBucket,
    ) {}
}
```

In the context of the exercise, `Solution` is a clear name and purpose. It is a pure data object. No code, just types. So there is nothing more to explain or put into the name.

To pass it back, it would look like this in your code:

```php
if ($this->first()->getAmount() === $this->goal) {
    return new Solution(
                $this->moves,
                $this->goalBucket,
                $this->otherBucket,
    );
}
```

Here also, the name is unambigious in that context. No intermediate variables required to explain anything further. One could add named arguments, but I think `new Solution()` says it all.

That is my thinking about a good name here. It is different from naming in a larger context, e.g. a library or module. I perhaps would choose a namespace to construct the context for `Solution` in a larger context, like `TwoBucket\Solution`. But for the exercise, the most simple name is enough.

2024-02-24 12:26 UTC, tomasnorre commented on exercises/practice/two-bucket/TwoBucket.php
> +class TwoBucket
```php
class Solution
{
    public function __construct(
        public int $numberOfActions,
        public string $nameOfBucketWithDesiredLiters,
        public int $litersLeftInOtherBucket,
    ) {}
}
```

Is this OK as you suggested? It's PHP 8.x code, and the project `composer.json` for exercism/php says `"php": "^7.4|^8.0",` which would not be true any more then. 

The tests are running against, `8.0`, `8.1` and `8.2` so that part isn't given any problems. Perhaps the Project `composer.json` simply needs and update?

2024-02-24 12:37 UTC, tomasnorre commented on exercises/practice/two-bucket/TwoBucket.php
> +class TwoBucket
I have committed a draft based on the assumption that PHP 8.x code is OK. The tests don't fail locally, at least.

2024-02-24 12:38 UTC, tomasnorre commented on exercises/practice/two-bucket/TwoBucket.php
> +    public function solve(): self
Did I get something wrong, or didn't we agree on the `Solution` object as return type now?

2024-02-24 12:58 UTC, mk-mxp commented on exercises/practice/two-bucket/TwoBucket.php
> +    public function solve(): self
In short: `Solution` for your code, not for the students interface.

The `Solution` object is your choice to implement the example code, which tells us: The exercise can be solved with PHP.

The interface to students should not require that exact `Solution` object. The students shall choose whatever they like to fulfill the tests. The mentors may tell them, that a typed return object is a better solution than a `stdObj` or properties on `$this`. Just as we discussed that. This way students learn to reason about their code and the way they do things. If there is only one way, there is no discussion, and less learning.

2024-02-24 14:10 UTC, tomasnorre commented on exercises/practice/two-bucket/TwoBucket.php
> +    public function solve(): self
OK. Think I got you know. I'll remove the return type on the `solve` function, but keep the tests as is. If they return a `Solution` object, `this` or `stdObject` isn't important as long as the object have the properties that we check for in the tests, is that correctly understood?

2024-02-24 14:12 UTC, mk-mxp commented on exercises/practice/two-bucket/TwoBucket.php
> +    public function solve(): self
Yes, that's all correct.

2024-02-24 14:14 UTC, tomasnorre commented on exercises/practice/two-bucket/TwoBucket.php
> +    public function solve(): self
I'm not running on all cylinders currently. Will fix and push.

2024-02-24 14:17 UTC, mk-mxp commented on exercises/practice/two-bucket/TwoBucket.php
> +class TwoBucket
About PHP version: We use PHP8.0+, I'll adjust `composer.json` these days.

2024-02-24 14:28 UTC, mk-mxp commented on exercises/practice/two-bucket/TwoBucket.php
> +    public function solve(): self
Thanks a lot for the discussion and the contribution. I'm very happy with it now. I'll wait until Monday evening CET before merging, so @neenjaw can veto on this. But I believe he won't.

2024-02-24 14:29 UTC, mk-mxp approved these changes

2024-02-24 15:50 UTC, neenjaw commented on exercises/practice/two-bucket/TwoBucket.php
> +    }
This interface is an improvement from the last, but since we don't have a meaning for what the buckets mean before the `solve` method is called, I think we should take one of these two options:

```
// Option A

class TwoBucket
{
    public function solve(int $sizeBucketOne, int $sizeBucketTwo, int $goal, string $startBucket)
    {
        // perform the solution for the parameters provided, return a solution object
    }
}

// or Option B

class TwoBucket
{
    public function __construct(int $sizeBucketOne, int $sizeBucketTwo, int $goal, string $startBucket)
    {
        // initialize and solve the solution, making the buckets available in getters
    }
}
```

If we have an object that requires its public methods to be called in a specific order before it is considered valid -- this is a cumbersome pattern that shifts the burden of implementation to the consumers of this object to understand the inner state of the object to use it correctly rather than the object being the expert on itself.

2024-02-24 17:28 UTC, mk-mxp commented on exercises/practice/two-bucket/TwoBucket.php
> +    }
Thanks for pointing that out. It is inherently a procedural problem, "input, process, output". Which means, the only feasable way to implement it is just a single function or method call.

2024-02-24 19:57 UTC, tomasnorre commented on exercises/practice/two-bucket/TwoBucket.php
> +    }
I opt for option A. I like that approach more than having the logic in the constructor. For me, the constructor is for setting up the Class/Object, not doing any logic. 

I think I'll manage to have it adjusted one of the following days, if either of you opt against it.

2024-02-25 18:55 UTC, merged

2024-02-25 18:57 UTC, mk-mxp commented
Thanks a lot for contributing! It took a bit longer to figure it out, but we are both learning about what's relevant for a good practice exercise.

2024-02-25 20:18 UTC, tomasnorre commented
> Thanks a lot for contributing! It took a bit longer to figure it out, but we are both learning about what's relevant for a good practice exercise.

You're welcome. It doesn't really matter how long it takes, as long as we keep the eye on the target and stay constructive in feedback and dialogue. 

I really appreciate inputs from both of you @mk-mxp and @neenjaw. 

I hope I can continue to bring quality work to the PHP track.