Add House Exercise
exercism/php pull request #647
Opened 2024-02-27 10:05 UTC by tomasnorre

2024-02-27 22:40 UTC, mk-mxp requested changes
Thanks for contribution! Only a small Markdown issue here.

This is one of the ["sing-song" exercises](https://github.com/exercism/php/issues/629#issuecomment-1959560962) @neenjaw suggested to skip. I do not know why, but maybe this should be the last exercise of that kind until we know the reasons. There is enough others to choose.

2024-02-27 22:40 UTC, mk-mxp commented on exercises/practice/house/.docs/instructions.md
> +> [The] process of placing a phrase of clause within another phrase of clause is called embedding.
```suggestion
> The process of placing a phrase of clause within another phrase of clause is called embedding.
```

2024-02-28 07:50 UTC, tomasnorre commented
> Thanks for contribution! Only a small Markdown issue here.
> 
> This is one of the ["sing-song" exercises](https://github.com/exercism/php/issues/629#issuecomment-1959560962) @neenjaw suggested to skip. I do not know why, but maybe this should be the last exercise of that kind until we know the reasons. There is enough others to choose.

I didn't think about that before completing it. I'm OK with rejecting it, too.

2024-02-28 11:38 UTC, mk-mxp approved these changes
Thanks - one last time for today - for contribution!

2024-02-28 11:41 UTC, merged