change : formula typo updated in pizza pi
exercism/php pull request #729
Opened 2024-06-05 06:44 UTC by fejan92

Updated the typo as suggested in the below issue 

https://github.com/exercism/php/issues/616

2024-06-05 12:15 UTC, mk-mxp requested changes
I hope I could clarify, what changes are needed. And thanks very much for adjusting the Markdown formatting!

2024-06-05 12:15 UTC, mk-mxp commented on exercises/concept/pizza-pi/.docs/instructions.md
> +Lilly calculated an equation to determine how many pizzas can of some diameter (d) made from a cheese cube of side-length (l):
This is one the 2 changes to the text, we want to have:

```suggestion
Lilly decided to use the following formula to determine how many pizzas of some diameter (d) can be made from a cheese cube of side-length (l):
```

2024-06-05 12:15 UTC, mk-mxp commented on exercises/concept/pizza-pi/.docs/instructions.md
> +- And returns the number of pizzas that can be made while rounding down.
And this is the second piece of text we would like to change, so it is more clear that the formular shown above must be implemented (and not the area of the pizza).

```suggestion
- And uses Lilly's formula to return the number of pizzas that can be made while rounding down.
```

2024-06-06 03:24 UTC, fejan92 commented
I just committed the changes you requested @mk-mxp.

Please review it. Thanks!

2024-06-07 12:20 UTC, mk-mxp approved these changes
Thanks for your contribution!

2024-06-07 12:22 UTC, merged