Change rna-transcription
exercism/php pull request #737
Opened 2024-06-09 06:12 UTC by fejan92

Changes which have been made till now.

- change: uuid and testdox added in test file for rna-transcription
- MD file formatted for rna-transcription
- remove: strict types from rna-transcription

Needs to be done for 

Decide on adding / adjusting / ordering test cases to match current problem specs
metadata: unsynced: rna-transcription

https://github.com/exercism/php/issues/730

2024-06-09 08:17 UTC, mk-mxp requested changes
Please use the UUIDs and descriptions from [problem specification `canonical-data.json`](https://github.com/exercism/problem-specifications/blob/main/exercises/rna-transcription/canonical-data.json).

Each test case has a `"uuid"` field to use with the `uuid` comment and a `"description"` field to use with `@testdox`. Also make sure, that `"input"` and `"expected"` are used in the test method, not other values.

In the end, please sort the tests according to the order in `canonical-data.json`, as this is the recommended test order.

Thanks for jumping in and helping!

2024-06-09 08:17 UTC, mk-mxp commented on exercises/practice/rna-transcription/.docs/instructions.md
> +```exercism/note
Doon't change the markdown files manually. Use `configlet` only.

2024-06-09 08:17 UTC, mk-mxp commented on exercises/practice/rna-transcription/.docs/introduction.md
> +```exercism/note
Same as before, do not edit the markdown files.

2024-06-09 08:17 UTC, mk-mxp commented on exercises/practice/rna-transcription/.meta/example.php
> -declare(strict_types=1);
We want to have `declare(strict_types=1);`, only the huge comment above it is useless in this file.

2024-06-09 08:17 UTC, mk-mxp commented on exercises/practice/rna-transcription/RnaTranscription.php
> -/*
In this file (the students stub file), we want to have this comment and the `declare(strict_types=1);` directive. In general, this file should not change at all.

2024-06-09 08:17 UTC, mk-mxp commented on exercises/practice/rna-transcription/RnaTranscriptionTest.php
> + * @uuid 123e4567-e89b-12d3-a456-426614174000
Why is this here?

2024-06-09 08:17 UTC, mk-mxp commented on exercises/practice/rna-transcription/RnaTranscriptionTest.php
> -declare(strict_types=1);
In the tests, we also want this directive. Remove the comment only.

2024-06-09 08:17 UTC, mk-mxp commented on exercises/practice/rna-transcription/RnaTranscriptionTest.php
> +     * @uuid 123e4567-e89b-12d3-a456-426614174001
In all the doc blocks above the tests:

`@uuid` is no valid annotation. We use a comment `uuid` only. Please change that.

```suggestion
     * uuid 123e4567-e89b-12d3-a456-426614174001
```

2024-06-09 08:37 UTC, fejan92 commented on exercises/practice/rna-transcription/.docs/instructions.md
> +```exercism/note
Ok I will update this.

2024-06-09 08:38 UTC, fejan92 commented on exercises/practice/rna-transcription/.meta/example.php
> -declare(strict_types=1);
Got it. Thanks!

2024-06-09 08:40 UTC, fejan92 commented on exercises/practice/rna-transcription/RnaTranscriptionTest.php
> + * @uuid 123e4567-e89b-12d3-a456-426614174000
I've added uuid in before class and each function also. Will update this also.

2024-06-09 08:43 UTC, mk-mxp commented on exercises/practice/rna-transcription/RnaTranscriptionTest.php
> + * @uuid 123e4567-e89b-12d3-a456-426614174000
Take a look at this file: https://github.com/exercism/php/blob/main/exercises/practice/yacht/YachtTest.php

No UUID for the class, or setUpBeforeClass, only the tests are identified by UUIDs

2024-06-09 10:26 UTC, mk-mxp commented
@fejan92 Are you still working on this? Click "Re-request review" next to my name in "Reviewers" when you are done.

> Needs to be done for
> 
> Decide on adding / adjusting / ordering test cases to match current problem specs

I took a look into the existing solutions. It is OK to add the missing test as specified in `canonical-data.json` https://github.com/exercism/problem-specifications/blob/main/exercises/rna-transcription/canonical-data.json The expected value you used is not OK.

2024-06-09 10:56 UTC, fejan92 commented
> canonical-data.json

I have update the test cases here. For `canonical-data.json` I need to clone that project and update the test cases there also.

2024-06-09 12:32 UTC, mk-mxp requested changes

2024-06-09 12:32 UTC, mk-mxp commented on exercises/practice/rna-transcription/RnaTranscriptionTest.php
>      }
`canonical-data.json` (https://github.com/exercism/problem-specifications/blob/main/exercises/rna-transcription/canonical-data.json) is **the source of test data** we use here in PHP track. That file has all data we need: the UUID, the description and the test cases.

All we do is write that data into our test file:

```suggestion
    /**
     * @testdox RNA complement
     * uuid 79ed2757-f018-4f47-a1d7-34a559392dbf
     */
    public function testTranscribesAllOccurrencesOne(): void
    {
        $this->assertSame('UGCACCAGAAUU', toRna('ACGTGGTCTTAA'));
    }
```

Do this for all tests. Remove the tests, that are not in `canonical-data.json`. Do not add new tests.

2024-06-10 08:59 UTC, mk-mxp commented
> Only `input` and `expected` remain to add in textdoc documentation
> 
> Please tell me if the below is proper documentation after that I will update in the test file
> 
> ```
>     /**
>      * @testdox RNA complement
>      * @input UGCACCAGAAUU
>      * @expected UCGGCCGUGAAAU
>      * uuid 79ed2757-f018-4f47-a1d7-34a559392dbf
>      */
>     public function testTranscribesAllOccurrencesOne(): void
>     {
>        ...body
>     }
> ```

No, thanks. Don't do that.

2024-06-10 09:03 UTC, mk-mxp approved these changes
Thanks a lot for helping with that! There was much to learn about the Exercism internals for you. Nice work!

2024-06-10 09:03 UTC, merged

2024-06-10 09:04 UTC, fejan92 commented
Thank you.

Hope I am not messing up things. Yes as a beginner I am making mistakes.