Change: remove strict types comment and updated test and test.toml file
exercism/php pull request #749
Opened 2024-06-13 06:22 UTC by fejan92

also added missing test cases

2024-06-13 06:45 UTC, fejan92 commented
@mk-mxp 

Need help 

I have added 3 new test cases with the below string and it failed.

```
子猫
Würstchenstand
ผู้เขียนโปรแกรม
```

I even tried to update the example code with `grapheme_extract` and `mb_substr` but still no success tests.

2024-06-13 16:13 UTC, mk-mxp commented
@fejan92 I'm too busy today. Thanks for your patience!

2024-06-14 04:42 UTC, fejan92 commented
Yeah, no problem.

There is no rush at all.

2024-06-14 07:24 UTC, mk-mxp requested changes
In `canonical-data.json` the failing tests are marked with `"scenarios": ["unicode"],`. In general, adding a scenario to an existing exercise will break too many things. So we only add them when other changes also make students code fail.

2024-06-14 07:24 UTC, mk-mxp commented on exercises/practice/reverse-string/.meta/tests.toml
> +description = "wide characters"
Most community solutions will fail for the unicode tests. Mark them as "not implemented" for this track like this:

```suggestion
[1bed0f8a-13b0-4bd3-9d59-3d0593326fa2]
description = "wide characters"
include=false
```

2024-06-14 07:24 UTC, mk-mxp commented on exercises/practice/reverse-string/ReverseStringTest.php
> +    }
Delete the unicode tests.

```suggestion
```

2024-06-18 06:56 UTC, mk-mxp approved these changes
Thank you for taking care of this! Again something learned about the inner workings of Exercism - I hope removing the new tests wasn't too frustating.

2024-06-18 06:56 UTC, merged