Sync protein-translation
exercism/php pull request #759
Opened 2024-06-22 11:25 UTC by fejan-malek

https://github.com/exercism/php/issues/743

2024-06-23 08:18 UTC, mk-mxp requested changes
That's a nice piece of work. Thank you!

2024-06-23 08:18 UTC, mk-mxp commented on exercises/practice/protein-translation/ProteinTranslationTest.php
> +     * @dataProvider invalidCodonDataProvider
Please make these test cases separate tests. See this issue for reasons: https://github.com/exercism/php/issues/755

Do not implement `uuid 1e75ea2a-f907-4994-ae5c-118632a1cb0f`, because it is replaced by `uuid 9eac93f3-627a-4c90-8653-6d0a0595bc6f` (see `tests.toml` and `"reimplements"` key in `canonical-data.json`.

If you want to read more about how this is connected, see https://github.com/exercism/problem-specifications/#changing-tests

2024-06-24 04:13 UTC, fejan-malek commented on exercises/practice/protein-translation/ProteinTranslationTest.php
> +     * @dataProvider invalidCodonDataProvider
Yes, I noticed the `reimplements` in the `test.toml` file also in another exercise. So if there is a `reimplements` keyword then we don't have to implement such test cases is that correct?

2024-06-24 11:26 UTC, mk-mxp commented on exercises/practice/protein-translation/ProteinTranslationTest.php
> +     * @dataProvider invalidCodonDataProvider
That's correct. Thank you!

2024-06-24 11:27 UTC, mk-mxp approved these changes

2024-06-24 11:29 UTC, merged