#48in24: anagram
exercism/php pull request #767
Opened 2024-06-27 03:46 UTC by fejan-malek

https://github.com/exercism/php/issues/734

-  Change: Added all the missing `testcases`
- Also removed unused `testcases`.

2024-06-28 12:05 UTC, mk-mxp commented
@fejan-malek You were too early with this one. 2024-07-23 minus 2 weeks = 2024-07-09. Please do not haste forward, it causes extra work.

I'll leave this opened. On 2024-07-09 (or some days after) please re-run the `configlet` sync command and rebase this branch. Thanks for your patience!

2024-07-09 13:58 UTC, mk-mxp requested changes
Thanks for the nice work! You are helping very much.

2024-07-10 07:29 UTC, fejan-malek commented on exercises/practice/anagram/AnagramTest.php
> +     * uuid dd40c4d2-3c8b-44e5-992a-f42b393ec373
I will keep it in mind. But past exercises are synced already in the same order of `@testdox` and `uuid`.

If we need to update that also then I will create a separate pull request.

2024-07-10 07:44 UTC, mk-mxp commented on exercises/practice/anagram/AnagramTest.php
> +     * uuid dd40c4d2-3c8b-44e5-992a-f42b393ec373
The past ecxercises were done in #773, thank you.

2024-07-13 07:54 UTC, mk-mxp approved these changes
Thanks a lot for helping with this one!

2024-07-13 07:54 UTC, merged