Sync Acronym
exercism/php pull request #769
Opened 2024-06-28 03:31 UTC by fejan-malek

https://github.com/exercism/php/issues/745

Below Changes done in this pull request
- Updated the Markdown file.
- New test cases added and removed tests which are not mentioned in `test.toml`

2024-06-28 11:42 UTC, fejan-malek commented
@mk-mxp Should I update the example code here?

Please review thanks!

2024-06-28 11:58 UTC, mk-mxp commented
> Please review thanks!

I hope to find time today. I'm busy with working for my living...

2024-06-28 12:33 UTC, mk-mxp requested changes

2024-06-28 12:33 UTC, mk-mxp commented on exercises/practice/acronym/AcronymTest.php
>      }
We cannot add apostrophes and underscores. The rules were not defined (and tested) before. These fail for all solutions that rely on `preg_*()` word boundary detection. And that is many.

So, please remove the last two tests (apostrophes and underscores). We only add the one with the long abbreviation and the consecutive delimiters.

Thanks!

2024-06-28 12:37 UTC, mk-mxp commented on exercises/practice/acronym/AcronymTest.php
>      }
@fejan-malek When you mark the excluded tests `include=false` in `tests.toml`, please add `comment=This invalidates existing solutions that rely on RegExp word boundary detection`.

2024-06-30 15:05 UTC, fejan-malek commented
@mk-mxp 

`testUnderscoreEmphasis`  Is working correctly?

Should I also add in not included in `test.toml`? If yes then what is the reason because it running with the existing solution?

2024-06-30 15:54 UTC, mk-mxp commented
No underscores, please. Reasons:

The `example.php` is an internal solution, showing that

* it is possible to solve the exercise in PHP
* a solution exists, that runs fast enough for exercisms infrastructure

It is not enough, that `example.php` can handle the new tests. We need to look at the community solutions for very common solutions.

There are currently about 350 different community solutions (see https://exercism.org/tracks/php/build > "Practice Exercises" > 106 active exercises > Acronym). These are shown partially on the exercise community solutions page (see https://exercism.org/tracks/php/exercises/acronym/solutions when you have solved the exercise / are not logged in). Many of them use `preg_*()` functions and rely on the word boundary detection (`\w` and others) of PCRE. An underscore is not seen as a word boundary by PCRE, so these solutions fail.

2024-07-02 14:26 UTC, mk-mxp requested changes
Why haven't I seen this earlier? Shame on me...

2024-07-02 14:26 UTC, mk-mxp commented on exercises/practice/acronym/AcronymTest.php
>          $this->assertEquals('PHP', acronym('PHP: Hypertext Preprocessor'));
```suggestion
        $this->assertEquals('GIMP', acronym('GNU Image Manipulation Program'));
```

2024-07-07 04:48 UTC, mk-mxp approved these changes
Thank you for contribution!

2024-07-07 04:49 UTC, merged