Sync Luhn
exercism/php pull request #780
Opened 2024-07-14 08:02 UTC by fejan-malek

https://github.com/exercism/php/issues/763

2024-07-14 08:05 UTC, fejan-malek commented
@mk-mxp 

Should I add a failed test in `included=false`?

The test cases failed.

`LuhnTest::testASimpleValidSINThatBecomesInvalidIfReversed`
`LuhnTest::testValidLuhnWithAnOddNumberOfDigitsAndNonZeroFirstDigit`

2024-07-15 15:29 UTC, mk-mxp commented
@fejan-malek I do not understand, why `example.php` passed the previous tests successfully and now doesn't pass those tests. I need to take a closer look at that, and hope to find time tomorrow.

Anything else looks great!

2024-07-16 08:37 UTC, mk-mxp requested changes

2024-07-16 08:37 UTC, mk-mxp commented on exercises/practice/luhn/LuhnTest.php
> +        $this->assertFalse(isValid("59"));
This is expected to be true by problem specifications:

```suggestion
        $this->assertTrue(isValid("59"));
```

2024-07-16 08:37 UTC, mk-mxp commented on exercises/practice/luhn/LuhnTest.php
> +        $this->assertTrue(isValid("109"));
This in fact shows a bug in our example solution. The first digit changes the result and our code does not take that into account. My own solution works :)

I tested a bunch of community solutions and found some of them failing, because they do not respect the old rule: Count positions from right to left for odd positions. So these fail for no new requirements, but an old one that wasn't properly tested for.

So, we add this test now. Your job: Adjust our solution, so it passes all tests. Thank you!

2024-07-20 14:01 UTC, mk-mxp commented on exercises/practice/luhn/LuhnTest.php
> +        $this->assertTrue(isValid("109"));
@fejan-malek I have some more time the next week: Do you want some help on this?

2024-08-03 07:39 UTC, mk-mxp commented
@fejan-malek Could you take this forward? Do you need help?

2024-08-06 05:18 UTC, fejan-malek commented
> @fejan-malek Could you take this forward? Do you need help?

Thanks for asking.

But still facing an error in the `LuhnTest::testValidLuhnWithAnOddNumberOfDigitsAndNonZeroFirstDigit` test case.

And also I am busy at work. Soon, I will work on this.

2024-08-24 08:03 UTC, mk-mxp approved these changes
Thank you for your great work!

2024-08-24 08:04 UTC, merged