Annalyn's Infiltration  - Task 4 - Instructions don't match tests
exercism/php pull request #786
Opened 2024-08-08 18:24 UTC by sarad1p1ty

As per #758:

- [X] Add a logic table (inputs and expected result) to exercises/concept/annalyns-infiltration/.meta/design.md to ensure proper wording of instructions for the future
- [ ] Find wording that matches the logic of the tests
- [X] Order tests to follow the sequence of instruction conditions (e.g. the first statement is "If Annalyn has her pet dog with her" -> first all tests "with dog" then all tests "without dog")
- [ ] Ask in forum about wording and logic issues of the new version
- [X] Rename exercise title to Annalyn's Infiltration (apostrophe added)

2024-08-09 10:18 UTC, mk-mxp commented
I think you can't look into the CI details, there are some formatting issues reported:

```
> phpcs

FILE: ...p/php/exercises/concept/annalyns-infiltration/AnnalynsInfiltrationTest.php
--------------------------------------------------------------------------------
FOUND 8 ERRORS AFFECTING 8 LINES
--------------------------------------------------------------------------------
 223 | ERROR | [x] Whitespace found at end of line
     |       |     (Squiz.WhiteSpace.SuperfluousWhitespace.EndLine)
 240 | ERROR | [x] Whitespace found at end of line
     |       |     (Squiz.WhiteSpace.SuperfluousWhitespace.EndLine)
 257 | ERROR | [x] Whitespace found at end of line
     |       |     (Squiz.WhiteSpace.SuperfluousWhitespace.EndLine)
 274 | ERROR | [x] Whitespace found at end of line
     |       |     (Squiz.WhiteSpace.SuperfluousWhitespace.EndLine)
 308 | ERROR | [x] Whitespace found at end of line
     |       |     (Squiz.WhiteSpace.SuperfluousWhitespace.EndLine)
 325 | ERROR | [x] Whitespace found at end of line
     |       |     (Squiz.WhiteSpace.SuperfluousWhitespace.EndLine)
 410 | ERROR | [x] Whitespace found at end of line
     |       |     (Squiz.WhiteSpace.SuperfluousWhitespace.EndLine)
 461 | ERROR | [x] Whitespace found at end of line
     |       |     (Squiz.WhiteSpace.SuperfluousWhitespace.EndLine)
```

2024-08-09 11:17 UTC, mk-mxp requested changes
Thanks for investing your time into this! Looking forward to merging soon.

2024-08-09 11:17 UTC, mk-mxp commented on exercises/concept/annalyns-infiltration/AnnalynsInfiltrationTest.php
>      }
One test case is missing to cover all combinations of Task 2:

```php
    /**
     * @testdox can spy when only the prisoner is asleep
     * @task_id 2
     */
    public function testCanSpyWhenOnlyPrisonerAsleep()
    {
        $infiltration = new AnnalynsInfiltration();
        $actual = $infiltration->canSpy(
            is_knight_awake: true,
            is_archer_awake: true,
            is_prisoner_awake: false
        );
        $expected = true;
        $this->assertEquals($expected, $actual);
    }
```

2024-08-09 13:47 UTC, sarad1p1ty commented on config.json
> +}
Thank you.

I'm afraid I'm having a little trouble with the CI tools. I am using VS Code locally, and thought I followed all instructions for installing configlet, but when I run `bin/configlet fmt` (or `composer run ci`), I am getting `Script bin/configlet fmt handling the configlet:fmt event returned with error code 1`

I'm not sure what I'm doing wrong.

2024-08-09 13:49 UTC, sarad1p1ty commented on exercises/concept/annalyns-infiltration/AnnalynsInfiltrationTest.php
>      }
Good spot! I have added this.

2024-08-09 13:57 UTC, mk-mxp commented on config.json
> +}
Troubleshooting external tools is so much fun! You are on a Linux machine or Windows, Apple, ...? `configlet` is not compiled for all architectures / systems, did `bin/fetch-configlet` actually download a binary to `bin/`?

2024-08-09 14:06 UTC, sarad1p1ty commented on config.json
> +}
Ah... oh dear.

Right, so I'm on a Windows 10 machine. So `fetch-configlet` seems to have downloaded `configlet.exe` to `bin`, yes.

2024-08-09 14:29 UTC, mk-mxp commented on config.json
> +}
Great! Runniing `bin/configlet.exe fmt` works`? Editing `composer.json` to use `bin/configlet.exe` works?

2024-08-09 15:03 UTC, mk-mxp commented on config.json
> +}
Great you found your way to fix this! CI is pleased :smiley:

2024-08-09 15:26 UTC, sarad1p1ty commented on config.json
> +}
Looks like this works now?

2024-08-09 15:41 UTC, mk-mxp commented on config.json
> +}
Yes, it works. Do you want to take an appraoch with the instructions or should I merge as it is? I'm OK with both.

2024-08-10 09:38 UTC, sarad1p1ty commented on config.json
> +}
Exciting!

If you're ok with merging as is, then that might be a good shout. "If it ain't broke..." :)

Thank you.

2024-08-11 05:27 UTC, mk-mxp approved these changes
Thanks for your contribution! There where no suggestions for wording changes in the forum, too.

2024-08-11 05:29 UTC, merged

2024-08-11 13:04 UTC, sarad1p1ty commented
Thank you! :D 
Is there anything else I can do?

2024-08-11 14:04 UTC, mk-mxp commented
@sarad1p1ty Did you look through the GitHub issues list? There is lots of things to do, with and without in-depth PHP / PHPUnit / Exercism knowledge. Synchronising exercises from the [common problem specifications repository](https://github.com/exercism/problem-specifications), adding missing exercises from that repository, adding concept exercises (adapted from other Exercism languages with similar concepts) aso. Pick something and I'll make an issue / forum thread with detailed instructions.