Fix: Various spellchecks
exercism/php pull request #835
Opened 2024-10-31 17:41 UTC by astyanax

I used various automated tools to determine mostly orthographic errors, but I edited whatever errors I could find.
I manually fixed everything (no automated edits).
I'm thinking that the "translater" change was an overkill, but I wanted to be pedantic

2024-10-31 20:21 UTC, tomasnorre commented
Thanks for you PR. As a lot of the spelling that you have correct come from https://github.com/exercism/problem-specifications , it would be great if you could create a PR against, that repository too. 

This will make sure that all tracks on exercism.org will profit from this change next time their exercises gets synced.

2024-10-31 23:28 UTC, homersimpsons commented
> This PR changes the API of some exercises, which will result in already completed exercises will fail. Therefor this can in my opinion not be merged, sorry. 
> 
> @mk-mxp, @neenjaw or @homersimpsons please way in here. 

Looking at the changes it seems that only the `ProteinTranslationTest.php` could impact the results (others are markdown files). But reading the change it is just a renaming of a class variable used within the test. This should have no effect on test outcome.

(I'm on mobile so maybe I didn't see another change)

About the suggestion to update problem-specifications repository I agree with that if those typos are there too.

2024-11-01 07:09 UTC, tomasnorre commented
> Looking at the changes it seems that only the `ProteinTranslationTest.php` could impact the results (others are markdown files). But reading the change it is just a renaming of a class variable used within the test. This should have no effect on test outcome.

I think you're right, I overlooked that the only changes done was in PHP was the test file. Shouldn't break anything.

2024-11-01 08:10 UTC, mk-mxp requested changes
Thanks a lot for these corrections! Just one small change required, where Search&Replace seems to have gone too far.

2024-11-01 08:10 UTC, mk-mxp commented on exercises/practice/protein-translation/ProteinTranslationTest.php
> +    public function testTranslatoRnaStrandToCorrectProteinList(): void
```suggestion
    public function testTranslateRnaStrandIntoCorrectProteinList(): void
```

2024-11-01 08:15 UTC, tasxatzial commented on exercises/practice/protein-translation/ProteinTranslationTest.php
> +    public function testTranslatoRnaStrandToCorrectProteinList(): void
This should be reverted, as the new name has some issues.

2024-11-01 08:19 UTC, tasxatzial commented on exercises/practice/protein-translation/ProteinTranslationTest.php
> +    public function testTranslatoRnaStrandToCorrectProteinList(): void
Dismiss my suggestion, as it's overridden by mk-mxp's. I hadn't seen the other reviews before posting my comment.

2024-11-05 15:37 UTC, astyanax commented
Thank you all for your comments and careful consideration, and thank you Tomas for the patch!

p.s. It'll take some time to grok `problem-specifications` and how `configlet` interacts with it, [#track-data-tooling](https://github.com/exercism/problem-specifications?tab=readme-ov-file#track-data-tooling) implies that corrections would need to be explicitly applied/overridden.

2024-11-05 16:10 UTC, mk-mxp approved these changes
Thanks everyone for contributing!

2024-11-05 16:10 UTC, merged