sync atbash-cipher
exercism/php pull request #847
Opened 2024-11-07 17:32 UTC by tomasnorre

Resolves #839

2024-11-11 16:37 UTC, tomasnorre commented
For some reason i get the `git rebase` wrong as I wanted to merge in the `ci: Allow for single exercise test exection`. Sorry for that.

2024-11-12 09:21 UTC, mk-mxp requested changes
Please add a function stub for `decode()` to the students file.

Everything else looks great, maybe a small improvement to ease the itches of an `array_search()` for each character.

2024-11-12 09:21 UTC, mk-mxp commented on exercises/practice/atbash-cipher/.meta/example.php
> +    $z_a = range('z', 'a');
You may use `array_combine()` to make a real lookup table and use `isset()` on it for checking if the input char can be decoded.

2024-11-12 14:42 UTC, tomasnorre commented
Better now?

2024-11-12 15:32 UTC, tomasnorre commented
I cannot reproduce the problem with the `composer lint:check` locally.

2024-11-12 15:44 UTC, mk-mxp commented
It's about to be solved: [We should follow PHPCS naming conventions as soon as possible](https://github.com/PHPCSStandards/PHP_CodeSniffer/issues/675).

2024-11-12 15:47 UTC, tomasnorre commented
> It's about to be solved: [We should follow PHPCS naming conventions as soon as possible](https://github.com/PHPCSStandards/PHP_CodeSniffer/issues/675).
> 
> If you want to provide a PR fixing it really, use `Commenting` category [like here](https://github.com/PHPCSStandards/PHP_CodeSniffer/wiki/Coding-Standard-Tutorial#creating-the-sniff).

I just saw it just now too.

2024-11-12 17:52 UTC, tomasnorre commented
> If you want to provide a PR fixing it really, use `Commenting` category [like here](https://github.com/PHPCSStandards/PHP_CodeSniffer/wiki/Coding-Standard-Tutorial#creating-the-sniff).

To be honest, I'm not sure where that fix lives?

2024-11-12 18:02 UTC, tomasnorre commented
> If you want to provide a PR fixing it really, use `Commenting` category [like here](https://github.com/PHPCSStandards/PHP_CodeSniffer/wiki/Coding-Standard-Tutorial#creating-the-sniff).

To be honest, i'm not sure how the fix would look like here. 
https://github.com/exercism/php/blob/main/src/Sniffs/ExplainStrictTypesSniff.php

2024-11-17 19:20 UTC, tomasnorre commented
This can be review PHPCS is working and MacOS fix is rebased into the PR.

2024-11-18 09:26 UTC, mk-mxp approved these changes
Thanks for all the work!

2024-11-18 09:27 UTC, merged