ci: Allow for single exercise test exection
exercism/php pull request #849
Opened 2024-11-08 16:46 UTC by tomasnorre

I often want to execute only one of the tests in the exercises when adjusting tests, to speed up the process. 

This PR will allow me to e.g. run only the tests for exercise `book-store` by adding an additional parameter.

It can be done in more way. 

```sh
composer test:run -- book-store
```

```sh
PHPUNIT_BIN='phpunit' bin/test.sh book-store 
```

I hope this will get accepted as it gives me a better workflow when updating the PHP track.

2024-11-09 10:12 UTC, mk-mxp requested changes
I like the workflow improvement! That's very welcome.

I haven't tested the suggested change, so take care. Using the `-name` filter allows wildcards like `b*`, too. Please test that this works also.

2024-11-09 10:12 UTC, mk-mxp commented on bin/test.sh
> +
We need to handle `practice` and `concept` differently (`example` vs. `exemplar`). So I suggest modifing the existing loops by adding the `-name` conditionally:

```suggestion
  name_filter=()
  if [ -n "$1" ]; then
    name_filter=("-name" "$1")
  fi
```

and later on:

```
  all_practice_exercise_dirs=$(find ./exercises/practice -maxdepth 1 -mindepth 1 -type d "${name_filter[@]}" | sort)
```

and

```
  all_concept_exercise_dirs=$(find ./exercises/concept -maxdepth 1 -mindepth 1 -type d "${name_filter[@]}" | sort)
```

2024-11-09 16:57 UTC, tomasnorre commented
Thanks for your feedback, will have a look at in the following days.

2024-11-09 20:37 UTC, tomasnorre commented
> Using the `-name` filter allows wildcards like `b*`, too. Please test that this works also.

This works if b* is wrapped in quotes.
``` 
$ composer test:run -- "b*" 
```

2024-11-09 20:38 UTC, tomasnorre commented
I'll have to check why it's failing, will look into it.

2024-11-10 08:21 UTC, mk-mxp commented
It fails, because the shell has `set -u` (fail on use of unbound variables). Therefore `[ $# -ge 1 ] && [ -n "$1" ]` is required, as you had it.

2024-11-11 07:59 UTC, merged