Sync book store
exercism/php pull request #850
Opened 2024-11-08 18:03 UTC by tomasnorre

Resolves #842 

There are some tests failing, with the example configuration. I had tested with my private implementation too, there some fails too. 

So I don't know if some tests aren't meant for the PHP track or what the deal is yet.

I Haven't made as detailed descriptions on the additional tests, they were more confusing than helpful to me.

2024-11-14 17:18 UTC, tomasnorre commented
q

2024-11-19 14:33 UTC, tomasnorre commented
Updated to match how I did it in the go-track, in that way it works.

2024-11-20 08:32 UTC, mk-mxp commented
@tomasnorre FYI: I am short of time until December. Please be patient...

2024-11-24 14:37 UTC, mk-mxp requested changes
Thanks for all the work! Just a tiny change required.

2024-11-24 14:37 UTC, mk-mxp commented on exercises/practice/book-store/.meta/example.php
> +function total(array $items): int
Please adjust the students stub in `BookStore.php` to match this interface. Also add a comment into the stub, something like:

```
// Note: we expect the total in cents (1$ = 100 cents).
```

2024-11-24 16:04 UTC, tomasnorre commented on exercises/practice/book-store/.meta/example.php
> +function total(array $items): int
Will do.

2024-12-08 09:14 UTC, mk-mxp approved these changes
Thanks for your patience. And thanks for your contribution!

2024-12-08 09:14 UTC, merged