ci: Fix strict types sniff
exercism/php pull request #857
Opened 2024-11-12 18:08 UTC by tomasnorre

Resolves the problem from Updating to `"squizlabs/php_codesniffer": "3.11.0"`

2024-11-12 18:11 UTC, tomasnorre commented
I'm a little confused that the exclude isn't respected anymore. From a quick glance all errors are from `example.php` or `*Test.php` which both should be excluded.

```
<rule ref="src/Sniffs/StrictTypes/ExplainStrictTypesSniff.php">
  <exclude-pattern>*/*Test\.php</exclude-pattern>
  <exclude-pattern>*/.meta/*\.php</exclude-pattern>
  <exclude-pattern>src/*</exclude-pattern>
  <exclude-pattern>contribution/*.php</exclude-pattern>
</rule>
```

2024-11-14 06:04 UTC, mk-mxp commented
Well, looks like the sniff name generation has gone wrong and so the excludes are not applied for our sniff. Would you mind opening an issue at PHPCodeSniffer and report the problem?

2024-11-15 12:12 UTC, tomasnorre commented
It's now working ready for review. 

I'm personally self in doubt about the `src/Exercism/` directory, if that should be called something else.

2024-11-16 09:20 UTC, mk-mxp requested changes
Which version of PHP CodeSniffer is required as a minimum, so that the name change works with the `exclude-pattern`? This should be set in `composer.json` `"require-dev": { "squizlabs/php_codesniffer": "^3.11.?" }` accordingly.

2024-11-16 09:20 UTC, mk-mxp commented on phpcs.xml
> +  <rule ref="src/Exercism/Sniffs/StrictTypes/ExplainStrictTypesSniff.php">
I think we should go for `src/Sniffs/StrictTypes/ExplainStrictTypesSniff.php`

That means, in `composer.json` we should have:

```json
  "autoload": {
    "Exercism\\Sniffs\\": "src/Sniffs",
    "Exercism\\Exercises\\": "exercises"
  }
```

and in `src/Sniffs/StrictTypes/ExplainStrictTypesSniff.php`

```php
namespace Exercism\Sniffs\StrictTypes;
```

2024-11-17 14:26 UTC, tomasnorre commented on phpcs.xml
> +  <rule ref="src/Exercism/Sniffs/StrictTypes/ExplainStrictTypesSniff.php">
But then we are running into the problem again, as we don't have 4 levels deep of directories.

2024-11-17 15:26 UTC, mk-mxp commented on phpcs.xml
> +  <rule ref="src/Exercism/Sniffs/StrictTypes/ExplainStrictTypesSniff.php">
Do we need to have a 4-level directory structure or a 4-level namespace / FQCN? I may have missed some of the discussion between you and jrnl, but it should be the namespace levels, not the file path: "The class name is already translated to a sniff name" from commit https://github.com/exercism/php/pull/857/commits/57395074618d7ac7fbc03dff48d32eeeb40d96ff of jrnl.

2024-11-17 17:03 UTC, tomasnorre commented on phpcs.xml
> +  <rule ref="src/Exercism/Sniffs/StrictTypes/ExplainStrictTypesSniff.php">
As I understand it. 4-lever directory. But after this PR https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/676/files, not anymore if I understand it correctly. 

That is merged and released. 

Our Sniff works again, but doesn't follow conventions yet. The #857 PR should fix that though. 

As the sniffs are working again with the 3.11.1 release, I would suggest us to merge the open PRs if they are ok. Then I'll look into this afterwards again, to have it on a clean main. 

Then we can take the right approach from there.

2024-11-18 09:24 UTC, mk-mxp commented on phpcs.xml
> +  <rule ref="src/Exercism/Sniffs/StrictTypes/ExplainStrictTypesSniff.php">
The PR from PHP_CodeSniffer you linked contains only changes handling the FQCN of sniffs. No line has anything to do with file pathes. So I still think, changing the autoload information and using the shorter directory structure is the right way to go.

2024-11-18 15:22 UTC, tomasnorre commented on phpcs.xml
> +  <rule ref="src/Exercism/Sniffs/StrictTypes/ExplainStrictTypesSniff.php">
I'll test it out.

2024-11-18 15:40 UTC, tomasnorre commented on phpcs.xml
> +  <rule ref="src/Exercism/Sniffs/StrictTypes/ExplainStrictTypesSniff.php">
The second I move the `Sniffs` on directory up (removing `Exercism`) out Sniffs excludes gets ignored. The sniff it's self is working, but not the `exclude-pattern`.

2024-11-18 16:20 UTC, mk-mxp commented on phpcs.xml
> +  <rule ref="src/Exercism/Sniffs/StrictTypes/ExplainStrictTypesSniff.php">
OK, thanks for trying that. So we have to keep the file path `src/Exercism/Sniffs/StrictTypes/ExplainStrictTypesSniff.php`.

If you still happen to have time for this: We could use the `namespace Exercism\Sniffs\StrictTypes;` and adjust `composer.json` `"autoload": { "Exercism\\Sniffs\\": "src/Exercism/Sniffs" }` accordingly? That would be an improvement, too.

2024-11-18 16:29 UTC, mk-mxp approved these changes

2024-11-19 08:06 UTC, mk-mxp approved these changes

2024-11-19 08:08 UTC, merged

2024-11-19 17:21 UTC, jrfnl commented on phpcs.xml
> +  <rule ref="src/Exercism/Sniffs/StrictTypes/ExplainStrictTypesSniff.php">
To be honest, for sniffs, you should generally not have a Composer `autoload` directive, but should let PHPCS handle the autoloading as the autoloading is integral to how PHPCS translates paths vs class names vs sniff codes.

If you follow the naming conventions, this will all work fine. If you don't and Composer autoloads the file, chances are that the translation between class name vs sniff code in PHPCS will not work correctly, which brings all sorts of problems.

2024-11-20 08:27 UTC, mk-mxp commented on phpcs.xml
> +  <rule ref="src/Exercism/Sniffs/StrictTypes/ExplainStrictTypesSniff.php">
Thank your pointing at that! I didn't know this might cause problems. Followed-up in #869