sync clock
exercism/php pull request #863
Opened 2024-11-15 20:34 UTC by tomasnorre

Resolves #845

2024-11-24 14:56 UTC, mk-mxp requested changes
Also we should have a comment in the students stub that missing methods need to be added.

2024-11-24 14:56 UTC, mk-mxp commented on exercises/practice/clock/ClockTest.php
> +        $this->assertEquals('08:00', $clock);
This is one of the magic tricks in PHP, but we currently have no concept (concept exercise) for students to learn this. So we should either explain the magic in the stub (for now) or explicitly call the method as done before:

```suggestion
        $this->assertEquals('08:00', $clock->__toString());
```

or

```suggestion
        $this->assertEquals('08:00', (string)$clock);
        // plus use `implements Stringable` in the students stub
        // plus a comment in the stub pointing to PHP docs on interface `Stringable`
```

@homersimpsons What do you think about this?

2024-12-08 10:12 UTC, mk-mxp requested changes
These changes are not connected to the discussion about the magic method usage.

Please add a comment to the students stub, that all missing methods need to be added by the student.

2024-12-08 10:12 UTC, mk-mxp commented on exercises/practice/clock/ClockTest.php
> +     * @testdox clocks with same time
And the last outer `cases` change:

```suggestion
     * @testdox Compare two clocks for equality - clocks with same time
```

2024-12-08 22:53 UTC, homersimpsons commented on exercises/practice/clock/ClockTest.php
> +        $this->assertEquals('08:00', $clock);
If we want to show magic methods with this exercise, I think I would prefer the explicit `(string)` cast, it has the advantages to clearly show that this method is magic.

But I do not know if we want to show those here.

I believe we could have a concept to show `__toString`, `__set`, `__get` which I think are rather "common". `__construct` is a magic method but I believe it is already being taught.

2024-12-21 09:49 UTC, mk-mxp approved these changes
Thanks for the contribution.

2024-12-21 09:49 UTC, mk-mxp commented on exercises/practice/clock/Clock.php
> +     */
Great!

2024-12-21 09:49 UTC, merged