sync darts
exercism/php pull request #867
Opened 2024-11-19 15:54 UTC by tomasnorre

Resolves #853

2024-12-14 12:35 UTC, mk-mxp commented
Discussion about a re-make in #853

2024-12-21 09:58 UTC, mk-mxp requested changes
Thanks for taking care of this!

2024-12-21 09:58 UTC, mk-mxp commented on exercises/practice/darts/.meta/example.php
> +function calculateScore(float $xAxis, float $yAxis): int
Canonical data uses `"property": "score",`, so we should use `score` as the functions name:

```suggestion
function score(float $xAxis, float $yAxis): int
```

2024-12-21 09:58 UTC, mk-mxp commented on exercises/practice/darts/Darts.php
> +function __construct(float $xAxis, float $yAxis)
```suggestion
function score(float $xAxis, float $yAxis): int
```

2024-12-21 09:58 UTC, mk-mxp commented on exercises/practice/darts/Darts.php
> +    throw new BadFunctionCallException("Please implement the Darts class!");
```suggestion
    throw new BadFunctionCallException("Please implement the __FUNCTION__ function!");
```

2024-12-21 10:37 UTC, tomasnorre commented on exercises/practice/darts/.meta/example.php
> +function calculateScore(float $xAxis, float $yAxis): int
My bad, will correct that later.

2024-12-21 16:26 UTC, mk-mxp approved these changes
Thanks a lot!

2024-12-21 16:27 UTC, merged